### PR TITLE
Added images for slideshow

### PR DESCRIPTION
**Pull request by Priyanshu-2005**
@aryamagarwal 

added images for slideshow
**_Path_**
`src/assets/for slideshow` 

all the images that i have added are inside `for slideshow` folder

if images are not good would add more of them 
also check out the images with extension `.avif` are they getting displayed on your system?

### CODE REVIEW

**Comment by aryamagarwal** [comment]
.avif file extensions are being displayed fine. 

But image size is not proper so yellow background is also getting visible. Check that.
Also I will be making Slides.js where you can assign slide number to the images. So that they come in a specified order.
image

**Comment by Priyanshu-2005** [comment]
if possible can you increase the width of each image

**Comment by Priyanshu-2005** [comment]
@aryamagarwal  also modified the login signup and forgot password 
kindly take a look at files changed option in github 

image


image

image



also if possible can you increase the width of each image

**Review by aryamagarwal — APPROVED** [review]

**Comment by aryamagarwal** [comment]
@Priyanshu-2005  Once Slideshow images issue is fixed I will merge the Login Page changes also, or make separate PR for that.

**Comment by aryamagarwal** [comment]
@Priyanshu-2005 I have merged it. Make a new PR for the final slideshow image changes.

**Pull request merged**
